Admin.php done
WChihWen/Win22IT262P4G4 pull request #5
Opened 2022-03-11 20:58 UTC by Helene-33

2022-03-12 18:15 UTC, WChihWen requested changes
Submitted a review, please let me know if you have any questions, thanks!

2022-03-12 18:15 UTC, WChihWen commented on admin.php
> +                    <h3 class="panel-title">'.$categoryName.' &nbsp;<a href="edit-category.php?CategoryID="><img src="images/edit.ico" alt="edit"></a></h3>
Here we need to post an ID to edit-category.
It is the missing variable needed to post.

```suggestion
                    <h3 class="panel-title">'.$categoryName.' &nbsp;<a href="edit-category.php?CategoryID='.(int)$row['CategoryID'].'"><img src="images/edit.ico" alt="edit"></a></h3>

```

2022-03-12 18:15 UTC, WChihWen commented on admin.php
> +                        echo '<li><a href="edit-feeds.php?CategoryName='.$categoryName.'&FeedsID='.(int)$rowfeeds['FeedsID'].'">'.stripslashes($rowfeeds['SubCategory']).' &nbsp; <img src="images/edit
I missed out on this point before. 
Here we just need to post a FeedsID.

```suggestion
                        echo '<li><a href="edit-feeds.php?FeedsID='.(int)$rowfeeds['FeedsID'].'">'.stripslashes($rowfeeds['SubCategory']).' &nbsp; <img src="images/edit.ico" alt="edit"></a></li>';

```

2022-03-12 18:20 UTC, WChihWen commented on admin.php
> +?>
Once you finish the changes, please click "Re-request review" circle icon next to my name, I will review it, thanks!

![image](https://user-images.githubusercontent.com/65738834/158029894-ae3549b4-8a92-4cfb-8556-6d84c39ca096.png)

2022-03-13 05:06 UTC, Helene-33 reviewed
I reviewed and committed the changes. I had them on my file but forgot to download them here... Let me know if it worked!

2022-03-13 19:50 UTC, WChihWen requested changes
The file is in the incorrect folder

2022-03-13 19:50 UTC, WChihWen commented on admin.php
> +<?php
`admin.php` should be in `Helene-33-admin.php-last-changes/rss/admin.php`

2022-03-13 19:50 UTC, WChihWen commented on admin.php
> +?>
@Helene-33 
When the codes, please click **"Re-request review"** as the screenshot, then I will receive the notification and I will review it, thank you!

2022-03-14 21:44 UTC, merged